# Generated by Django 3.0.3 on 2020-02-24 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
