# Generated by Django 3.0.3 on 2020-02-24 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0002_wishlist_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='name',
            field=models.CharField(blank=True, default='DEFAULT VALUE', max_length=30, null=True),
        ),
    ]
