# Generated by Django 3.0.3 on 2020-02-24 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0003_auto_20200224_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
