# Generated by Django 3.0.3 on 2020-03-01 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0008_wishlistitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smallwishlist',
            name='name',
            field=models.CharField(default='Wishlist', max_length=30),
        ),
    ]
