# Generated by Django 3.0.2 on 2020-02-28 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200227_1427'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=5)),
                ('city', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Credit_Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cc_number', models.CharField(max_length=30)),
                ('cc_expiration', models.CharField(max_length=10)),
                ('cc_security_code', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='home_address',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='shipping_address',
        ),
        migrations.AddField(
            model_name='profile',
            name='payment_info',
            field=models.ManyToManyField(to='user.Credit_Card'),
        ),
        migrations.AddField(
            model_name='profile',
            name='home_address',
            field=models.ManyToManyField(related_name='home_address', to='user.Address'),
        ),
        migrations.AddField(
            model_name='profile',
            name='shipping_address',
            field=models.ManyToManyField(related_name='shipping_address', to='user.Address'),
        ),
    ]
